[project]
authors = ["David W.H. Swenson <dwhs@hyperblazer.net>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "oop"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
numpy = "*"
matplotlib = "*"
jupyterlab = "*"
